-- Create table for feedback submissions
create table feedback_submissions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  full_name text not null,
  company_name text not null,
  email text not null,
  satisfaction_overall text,
  material_usefulness text,
  speaker_interest text,
  attend_again text,
  recommend_colleagues text,
  comments text
);

-- Enable RLS
alter table feedback_submissions enable row level security;

-- Allow inserts from anyone (anon)
create policy "Enable insert for everyone" on feedback_submissions for insert with check (true);

-- Allow select only for authenticated (if needed, or just admin)
create policy "Enable read access for authenticated users only" on feedback_submissions for select using (auth.role() = 'authenticated');

-- Add new columns for toolkit interest and privacy consent
ALTER TABLE feedback_submissions ADD COLUMN toolkit_interest text;
ALTER TABLE feedback_submissions ADD COLUMN privacy_consent boolean DEFAULT false;
